spring:
  application:
    name: daijiaguanli
  datasource:
    dynamic:
      primary: coupon
      strict: true
      datasource:
        coupon:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://gmalldocker_mysql:3306/daijia_coupon?useSSL=false&serverTimezone=UTC
          username: root
          password: TheAttackerIsSB321
        customer:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://gmalldocker_mysql:3306/daijia_customer?useSSL=false&serverTimezone=UTC
          username: root
          password: TheAttackerIsSB321
        dispatch:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://gmalldocker_mysql:3306/daijia_dispatch?useSSL=false&serverTimezone=UTC
          username: root
          password: TheAttackerIsSB321
        driver:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://gmalldocker_mysql:3306/daijia_driver?useSSL=false&serverTimezone=UTC
          username: root
          password: TheAttackerIsSB321
        order:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://gmalldocker_mysql:3306/daijia_order?useSSL=false&serverTimezone=UTC
          username: root
          password: TheAttackerIsSB321
        payment:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://gmalldocker_mysql:3306/daijia_payment?useSSL=false&serverTimezone=UTC
          username: root
          password: TheAttackerIsSB321
        rule:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://gmalldocker_mysql:3306/daijia_rule?useSSL=false&serverTimezone=UTC
          username: root
          password: TheAttackerIsSB321
        system:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://gmalldocker_mysql:3306/daijia_system?useSSL=false&serverTimezone=UTC
          username: root
          password: TheAttackerIsSB321
      hikari:
        max-lifetime: 1800000
        maximum-pool-size: 10
        minimum-idle: 5
  data:
    redis:
      host: gmalldocker_redis
      port: 6379
      password: dashabi321
server:
  port: 8888
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    root: debug
    com.baomidou.dynamic.datasource: debug
    org.springframework.boot: debug
    org.mybatis: debug

